# Create logistic regression to predict 

# import library

In [186]:
#coding: utf-8
import pandas as pd 
import numpy as np

# Create linear regression to predict absent

In [226]:
df_Absent=pd.read_csv("Absent_preprosessing.csv")
df_Absent.head()

Reason1  Reason2  Reason3  Reason4  Month value  Day of week  \
0        0        0        0        1            7            7   
1        0        0        0        0            7           14   
2        0        0        0        1            7           15   
3        1        0        0        0            7           16   
4        0        0        0        1            7           23   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [ ]:
#delete all the unname column
#df_Absent=df_Absent.drop(columns='Unnamed: 0')
df_Absent

# Create target (Choose which column is useful for the prediction)

In [ ]:
#find med to classify the consistantcy of absent (if>med : High absent), (if < med : Low absent)
med_abesnt=df_Absent["Absenteeism Time in Hours"].median()

In [ ]:
#create targets Extreamly high(1): Absent hour >= 4 Moderately High(0): Absent hour <=3
#target=[]
#for n in df_Absent["Absenteeism Time in Hours"]:
#    if n>3:
#       target.append(1)
#    if n<=3:
#       target.append(0)

#target=pd.DataFrame(target,columns=["Target"])


#or using >>>> where
target=np.where(df_Absent["Absenteeism Time in Hours"]>med_abesnt,1,0)
target


# Create new column 

In [ ]:
df_Absent["Excessive Absenteeism"]=target
df_target=df_Absent.drop(columns="Absenteeism Time in Hours")
df_target

In [ ]:
#Y.shape is (n,m). So Y.shape[0] is n.
#find percentage of excessive absent
print((target.sum()/target.shape[0])*100,"%")

# Select inputs for regrssion

In [ ]:
df_target.shape

In [ ]:
unscale_input=df_target.iloc[:,0:14] #or df_input=df_target.iloc[:,:-1] would be more appropriate 
unscale_input

# Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler 
#Standardize features by removing the mean and scaling to unit variance
#z = (x - u) / s
absenteeism_scaler=StandardScaler()
#StandardScaler() will normalize the features (each column of X) so that each column/feature/variable will have 
#mean = 0 and standard deviation = 1

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler
class CustomScaler (BaseEstimator, TransformerMixin):
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns=columns
        self.mean=None
        self.var=None
    def fit(self, X,y=None):
        self.scaler.fit(X[self.columns],y)
        self.mean=np.mean(X[self.columns])
        self.var=np.var(X[self.columns])
        return self
    def transform(self, X,y=None,copy=None):
        init_col_order=X.columns
        X_scale=pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scale=X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scale,X_scale],axis=1)[init_col_order]
    
        



In [ ]:
unscale_input.columns.values

In [ ]:
columns_to_scale=['Month value', 'Day of week', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'] #don't use dummies 

In [188]:
unscale_input

Reason1  Reason2  Reason3  Reason4  Month value  Day of week  \
0          0        0        0        1            7            7   
1          0        0        0        0            7           14   
2          0        0        0        1            7           15   
3          1        0        0        0            7           16   
4          0        0        0        1            7           23   
5          0        0        0        1            7           10   
6          0        0        0        1            7           17   
7          0        0        0        1            7           24   
8          0        0        1        0            7            6   
9          0        0        0        1            7           13   
10         1        0        0        0            7           20   
11         1        0        0        0            7           14   
12         1        0        0        0            7           15   
13         1        0        0        0            7           15   
14         0        0        0        1            7           15   
15         1        0        0        0            7           17   
16         0        0        0        1            7           17   
17         0        0        1        0            7           27   
18         1        0        0        0            7           30   
19         0        0        0        1            8            5   
20         1        0        0        0            8           12   
21         1        0        0        0            8            3   
22         1        0        0        0            8           10   
23         0        0        0        1            8           14   
24         0        0        1        0            8           17   
25         0        0        0        1            8           24   
26         0        0        0        1            8            4   
27         0        0        0        1            8           12   
28         0        0        1        0            8           19   
29         0        0        0        1            8           28   
..       ...      ...      ...      ...          ...          ...   
670        0        0        0        1            4           24   
671        0        0        1        0            4           26   
672        1        0        0        0            4           26   
673        0        0        0        1            4           27   
674        0        0        0        1            5            7   
675        0        0        1        0            5            9   
676        0        0        0        1            5            9   
677        1        0        0        0            5            9   
678        0        0        0        1            5            9   
679        1        0        0        0            5           10   
680        0        0        0        1            5           10   
681        1        0        0        0            5           10   
682        0        0        1        0            5           11   
683        0        0        0        1            5           11   
684        0        0        0        1            5           11   
685        0        0        0        1            5           14   
686        1        0        0        0            5           15   
687        0        0        0        1            5           15   
688        0        0        0        0            5           15   
689        0        0        0        1            5           16   
690        0        0        0        0            5           16   
691        0        1        0        0            5           18   
692        1        0        0        0            5           21   
693        1        0        0        0            5           21   
694        0        0        0        1            5           23   
695        1        0        0        0            5           23   
696

In [189]:
absenteeism_scaler=CustomScaler(columns_to_scale)

In [190]:
absenteeism_scaler.fit(unscale_input) 

/Users/pinnytu/anaconda2/lib/python3.6/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


CustomScaler(columns=['Month value', 'Day of week', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children', 'Pets'],
       copy=None, with_mean=None, with_std=None)

In [191]:
scale_input=absenteeism_scaler.transform(unscale_input) 
scale_input

/Users/pinnytu/anaconda2/lib/python3.6/site-packages/ipykernel_launcher.py:17: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


Reason1  Reason2  Reason3  Reason4  Month value  Day of week  \
0          0        0        0        1     0.182726    -1.103121   
1          0        0        0        0     0.182726    -0.228337   
2          0        0        0        1     0.182726    -0.103367   
3          1        0        0        0     0.182726     0.021602   
4          0        0        0        1     0.182726     0.896386   
5          0        0        0        1     0.182726    -0.728213   
6          0        0        0        1     0.182726     0.146571   
7          0        0        0        1     0.182726     1.021355   
8          0        0        1        0     0.182726    -1.228090   
9          0        0        0        1     0.182726    -0.353306   
10         1        0        0        0     0.182726     0.521479   
11         1        0        0        0     0.182726    -0.228337   
12         1        0        0        0     0.182726    -0.103367   
13         1        0        0        0     0.182726    -0.103367   
14         0        0        0        1     0.182726    -0.103367   
15         1        0        0        0     0.182726     0.146571   
16         0        0        0        1     0.182726     0.146571   
17         0        0        1        0     0.182726     1.396263   
18         1        0        0        0     0.182726     1.771171   
19         0        0        0        1     0.468236    -1.353059   
20         1        0        0        0     0.468236    -0.478275   
21         1        0        0        0     0.468236    -1.602998   
22         1        0        0        0     0.468236    -0.728213   
23         0        0        0        1     0.468236    -0.228337   
24         0        0        1        0     0.468236     0.146571   
25         0        0        0        1     0.468236     1.021355   
26         0        0        0        1     0.468236    -1.478029   
27         0        0        0        1     0.468236    -0.478275   
28         0        0        1        0     0.468236     0.396509   
29         0        0        0        1     0.468236     1.521232   
..       ...      ...      ...      ...          ...          ...   
670        0        0        0        1    -0.673803     1.021355   
671        0        0        1        0    -0.673803     1.271294   
672        1        0        0        0    -0.673803     1.271294   
673        0        0        0        1    -0.673803     1.396263   
674        0        0        0        1    -0.388293    -1.103121   
675        0        0        1        0    -0.388293    -0.853183   
676        0        0        0        1    -0.388293    -0.853183   
677        1        0        0        0    -0.388293    -0.853183   
678        0        0        0        1    -0.388293    -0.853183   
679        1        0        0        0    -0.388293    -0.728213   
680        0        0        0        1    -0.388293    -0.728213   
681        1        0        0        0    -0.388293    -0.728213   
682        0        0        1        0    -0.388293    -0.603244   
683        0        0        0        1    -0.388293    -0.603244   
684        0        0        0        1    -0.388293    -0.603244   
685        0        0        0        1    -0.388293    -0.228337   
686        1        0        0        0    -0.388293    -0.103367   
687        0        0        0        1    -0.388293    -0.103367   
688        0        0        0        0    -0.388293    -0.103367   
689        0        0        0        1    -0.388293     0.021602   
690        0        0        0        0    -0.388293     0.021602   
691        0        1        0        0    -0.388293     0.271540   
692        1        0        0        0    -0.388293     0.646448   
693        1        0        0        0    -0.388293     0.646448   
694        0        0        0        1    -0.388293     0.896386   
695        1        0        0        0    -0.388293     0.896386   
696

In [192]:
#fit(X[, y])	Compute the mean and std to be used for later scaling
#transform(X[, y, copy])	Perform standardization by centering and scaling

#scale_input=absenteeism_scaler.fit_transform(unscale_input) 
#scale_input    

In [193]:
scale_input.mean(axis=0) #mean close to 0  

Reason1                    2.500000e-01
Reason2                    8.571429e-03
Reason3                    9.000000e-02
Reason4                    5.971429e-01
Month value               -3.868334e-16
Day of week                4.821540e-17
Transportation Expense    -1.703399e-16
Distance to Work           1.261689e-16
Age                        1.221245e-16
Daily Work Load Average    9.538402e-16
Body Mass Index            5.424232e-17
Education                  2.561443e-16
Children                  -1.058380e-16
Pets                      -2.973019e-16
dtype: float64

In [194]:
scale_input.std(axis=0) #std close to 1 

Reason1                    0.433322
Reason2                    0.092250
Reason3                    0.286386
Reason4                    0.490823
Month value                1.000715
Day of week                1.000715
Transportation Expense     1.000715
Distance to Work           1.000715
Age                        1.000715
Daily Work Load Average    1.000715
Body Mass Index            1.000715
Education                  1.000715
Children                   1.000715
Pets                       1.000715
dtype: float64

# Split the data into train, test & shuffle

In [195]:
from sklearn.model_selection import train_test_split

In [196]:
X_train,X_test,y_train,y_test= train_test_split(scale_input,target)

In [197]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(525, 14) (525,)
(175, 14) (175,)


# Logistic regression with sklearn

In [198]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

Training the model

In [199]:
reg=LogisticRegression()
reg.fit(X_train,y_train)

/Users/pinnytu/anaconda2/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [200]:
#.score(inputs,targets) return mean accuracy on the given test data and labels
reg.score(X_train,y_train) #model learn to classify ~ 75% correctly

0.7619047619047619

# Manaully check the accuracy

In [201]:
model_output=reg.predict(X_train)
model_output

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,

In [202]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,

In [203]:
model_output == y_train

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True, False,  True, False,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True, False, False, False,
        True,  True, False,  True,  True,  True,  True,  True, False,
       False,  True, False,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True,

In [204]:
(np.sum(model_output==y_train)/model_output.shape[0])*100 #find TRUE %  #get the same result as using 'score '

76.19047619047619

# Finding intercept(b1) and coefficient(b2,b3..) of linear/logistic regression 
y=b1+b2X1+b3X2+b4X3+...

In [205]:
reg.intercept_

array([-1.52726691])

In [206]:
reg.coef_

array([[ 2.72561273,  0.72239116,  2.77112163,  0.76185256,  0.02839126,
        -0.05073325,  0.66812936, -0.05128134, -0.10428782,  0.02293065,
         0.2289355 ,  0.0692117 ,  0.35394673, -0.28900301]])

Create new table contain header of each column and intercept + coef in this order

In [207]:
feature_col=unscale_input.columns.values
feature_col

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month value',
       'Day of week', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [208]:
reg.coef_


array([[ 2.72561273,  0.72239116,  2.77112163,  0.76185256,  0.02839126,
        -0.05073325,  0.66812936, -0.05128134, -0.10428782,  0.02293065,
         0.2289355 ,  0.0692117 ,  0.35394673, -0.28900301]])

In [209]:
data={"Features": feature_col, "Coefficient": reg.coef_[0][:]}

In [210]:
summary_df=pd.DataFrame(data)
summary_df

Features  Coefficient
0                   Reason1     2.725613
1                   Reason2     0.722391
2                   Reason3     2.771122
3                   Reason4     0.761853
4               Month value     0.028391
5               Day of week    -0.050733
6    Transportation Expense     0.668129
7          Distance to Work    -0.051281
8                       Age    -0.104288
9   Daily Work Load Average     0.022931
10          Body Mass Index     0.228935
11                Education     0.069212
12                 Children     0.353947
13                     Pets    -0.289003

In [211]:
summary_df.index.values[1:14]
summary_df

Features  Coefficient
0                   Reason1     2.725613
1                   Reason2     0.722391
2                   Reason3     2.771122
3                   Reason4     0.761853
4               Month value     0.028391
5               Day of week    -0.050733
6    Transportation Expense     0.668129
7          Distance to Work    -0.051281
8                       Age    -0.104288
9   Daily Work Load Average     0.022931
10          Body Mass Index     0.228935
11                Education     0.069212
12                 Children     0.353947
13                     Pets    -0.289003

In [212]:
summary_df.index = summary_df.index + 1
summary_df.loc[0]=["Intercept",reg.intercept_[0]]

conclude_df=summary_df.sort_index()
conclude_df

Features  Coefficient
0                 Intercept    -1.527267
1                   Reason1     2.725613
2                   Reason2     0.722391
3                   Reason3     2.771122
4                   Reason4     0.761853
5               Month value     0.028391
6               Day of week    -0.050733
7    Transportation Expense     0.668129
8          Distance to Work    -0.051281
9                       Age    -0.104288
10  Daily Work Load Average     0.022931
11          Body Mass Index     0.228935
12                Education     0.069212
13                 Children     0.353947
14                     Pets    -0.289003

# Interpreting the Coeff

In [213]:
conclude_df["Odds_ratio"]=np.exp(conclude_df.Coefficient)
conclude_df

Features  Coefficient  Odds_ratio
0                 Intercept    -1.527267    0.217128
1                   Reason1     2.725613   15.265765
2                   Reason2     0.722391    2.059352
3                   Reason3     2.771122   15.976544
4                   Reason4     0.761853    2.142241
5               Month value     0.028391    1.028798
6               Day of week    -0.050733    0.950532
7    Transportation Expense     0.668129    1.950585
8          Distance to Work    -0.051281    0.950011
9                       Age    -0.104288    0.900966
10  Daily Work Load Average     0.022931    1.023196
11          Body Mass Index     0.228935    1.257261
12                Education     0.069212    1.071663
13                 Children     0.353947    1.424679
14                     Pets    -0.289003    0.749010

In [214]:
conclude_df=conclude_df.sort_values("Odds_ratio",ascending=False) #Odds ratio max to min 
conclude_df  #Feature not important if coeff~1 or oddsratio~0   
#furture away from 0 a coeff is, the bigger its important

Features  Coefficient  Odds_ratio
3                   Reason3     2.771122   15.976544
1                   Reason1     2.725613   15.265765
4                   Reason4     0.761853    2.142241
2                   Reason2     0.722391    2.059352
7    Transportation Expense     0.668129    1.950585
13                 Children     0.353947    1.424679
11          Body Mass Index     0.228935    1.257261
12                Education     0.069212    1.071663
5               Month value     0.028391    1.028798
10  Daily Work Load Average     0.022931    1.023196
6               Day of week    -0.050733    0.950532
8          Distance to Work    -0.051281    0.950011
9                       Age    -0.104288    0.900966
14                     Pets    -0.289003    0.749010
0                 Intercept    -1.527267    0.217128

#from the table we can assume that 'Education, Month value, Daily work load, Distance to work ' is close to 0 => smallest impact
#reason 1 = various diseases
#reason 2 = pregnancy and giving birth
#reason 3= poisoning
#reason 4 = light diseases

#get P-value , and elliminate coeff with p-valu>0.05


# Testing the model

In [215]:
reg.score(X_test,y_test)

0.7885714285714286

In [216]:
model_output #X_train 

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,

In [217]:
predict_prob = reg.predict_proba(X_test) #find prob of being 0(1st col) and 1(2nd col) 
predict_prob

array([[0.46390531, 0.53609469],
       [0.74657948, 0.25342052],
       [0.65704796, 0.34295204],
       [0.86619238, 0.13380762],
       [0.28500586, 0.71499414],
       [0.54656048, 0.45343952],
       [0.08868228, 0.91131772],
       [0.75251942, 0.24748058],
       [0.73311966, 0.26688034],
       [0.81955923, 0.18044077],
       [0.1147332 , 0.8852668 ],
       [0.82050293, 0.17949707],
       [0.48841269, 0.51158731],
       [0.81632856, 0.18367144],
       [0.30196424, 0.69803576],
       [0.09180965, 0.90819035],
       [0.74054813, 0.25945187],
       [0.65104546, 0.34895454],
       [0.79311363, 0.20688637],
       [0.30036888, 0.69963112],
       [0.09304042, 0.90695958],
       [0.73684474, 0.26315526],
       [0.26453952, 0.73546048],
       [0.16379684, 0.83620316],
       [0.40146996, 0.59853004],
       [0.25143224, 0.74856776],
       [0.39674728, 0.60325272],
       [0.5715094 , 0.4284906 ],
       [0.285085  , 0.714915  ],
       [0.7306519 , 0.2693481 ],
       [0.

In [218]:
predict_prob[:,0]

array([0.46390531, 0.74657948, 0.65704796, 0.86619238, 0.28500586,
       0.54656048, 0.08868228, 0.75251942, 0.73311966, 0.81955923,
       0.1147332 , 0.82050293, 0.48841269, 0.81632856, 0.30196424,
       0.09180965, 0.74054813, 0.65104546, 0.79311363, 0.30036888,
       0.09304042, 0.73684474, 0.26453952, 0.16379684, 0.40146996,
       0.25143224, 0.39674728, 0.5715094 , 0.285085  , 0.7306519 ,
       0.77989478, 0.7835942 , 0.08505969, 0.78560411, 0.40337608,
       0.78786373, 0.24978642, 0.08534308, 0.1892224 , 0.07563005,
       0.79518652, 0.08169226, 0.59114169, 0.22466053, 0.5029491 ,
       0.38503367, 0.86608645, 0.60449421, 0.77583681, 0.84746097,
       0.20089189, 0.7927987 , 0.5725968 , 0.25854587, 0.25485021,
       0.32044314, 0.2646692 , 0.5688196 , 0.78228429, 0.81774421,
       0.35078893, 0.14922228, 0.42876118, 0.62887123, 0.44235428,
       0.86619238, 0.5078581 , 0.77030424, 0.40166688, 0.81111616,
       0.78033578, 0.51897326, 0.0720841 , 0.74806867, 0.74510

# Save the model

In [219]:
#pickle[module] = module use to convert python to char stream 
#Pickling is used to store python objects. This means things like lists, dictionaries, class objects, and more
import pickle 

In [220]:
with open ('model','wb') as file: #model=filename #wb=writebytes
    pickle.dump(reg,file) #dump = save reg in file  

In [221]:
with open ('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)

In [222]:
loaded_model = pickle.load(open('model', 'rb'))
loaded_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [223]:
#with open ('scaler', 'wb') as file:
   #     json.dump(absenteeism_scaler,file)

In [224]:
loaded_model2 = pickle.load(open('scaler', 'rb'))
loaded_model2 

CustomScaler(columns=['Month value', 'Day of week', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children', 'Pets'],
       copy=None, with_mean=None, with_std=None)